[
    {
        "collegeName": "IIT Delhi",
        "generalSeats": 20,
        "obcSeats": 10,
        "collegeId": 1,
        "stRank": 1000,
        "scRank": 2000,
        "generalRank": 5000,
        "obcRank": 3000,
        "branch": "CS",
        "boardPercentage": 70,
        "scSeats": 6,
        "stSeats": 10
    },
    {
        "collegeName": "IIT Delhi",
        "generalSeats": 20,
        "obcSeats": 12,
        "collegeId": 1,
        "stRank": 2000,
        "scRank": 3500,
        "generalRank": 10000,
        "obcRank": 7000,
        "branch": "IT",
        "boardPercentage": 70,
        "scSeats": 10,
        "stSeats": 12
    },
    {
        "collegeName": "IIT Delhi",
        "generalSeats": 29,
        "obcSeats": 10,
        "collegeId": 1,
        "stRank": 2000,
        "scRank": 2400,
        "generalRank": 12000,
        "obcRank": 8000,
        "branch": "ECE",
        "boardPercentage": 70,
        "scSeats": 9,
        "stSeats": 11
    },
    {
        "collegeName": "MNIT Jaipur",
        "generalSeats": 20,
        "obcSeats": 15,
        "collegeId": 2,
        "stRank": 1500,
        "scRank": 2500,
        "generalRank": 10000,
        "obcRank": 4000,
        "branch": "CS",
        "boardPercentage": 75,
        "scSeats": 10,
        "stSeats": 12
    },
    {
        "collegeName": "MNIT Jaipur",
        "generalSeats": 26,
        "obcSeats": 11,
        "collegeId": 2,
        "stRank": 2000,
        "scRank": 3000,
        "generalRank": 15000,
        "obcRank": 6000,
        "branch": "IT",
        "boardPercentage": 75,
        "scSeats": 7,
        "stSeats": 10
    },
    {
        "collegeName": "MNIT Jaipur",
        "generalSeats": 19,
        "obcSeats": 19,
        "collegeId": 2,
        "stRank": 2200,
        "scRank": 3200,
        "generalRank": 11000,
        "obcRank": 6500,
        "branch": "ECE",
        "boardPercentage": 75,
        "scSeats": 7,
        "stSeats": 18
    },
    {
        "collegeName": "BIT sindri",
        "generalSeats": 23,
        "obcSeats": 9,
        "collegeId": 3,
        "stRank": 2000,
        "scRank": 1500,
        "generalRank": 12000,
        "obcRank": 4000,
        "branch": "CS",
        "boardPercentage": 80,
        "scSeats": 13,
        "stSeats": 10
    },
    {
        "collegeName": "BIT sindri",
        "generalSeats": 18,
        "obcSeats": 12,
        "collegeId": 3,
        "stRank": 2100,
        "scRank": 1700,
        "generalRank": 14000,
        "obcRank": 4500,
        "branch": "IT",
        "boardPercentage": 80,
        "scSeats": 8,
        "stSeats": 10
    },
    {
        "collegeName": "BIT sindri",
        "generalSeats": 19,
        "obcSeats": 11,
        "collegeId": 3,
        "stRank": 2400,
        "scRank": 2000,
        "generalRank": 15000,
        "obcRank": 5000,
        "branch": "ECE",
        "boardPercentage": 80,
        "scSeats": 9,
        "stSeats": 4
    }
]